<div id="myGrid" style="height:calc(100vh - 270px);" class="ag-theme-alpine mb-3"></div>
<script src="<?php echo URL_ASSETS ?>/js/ag-grid-enterprise.js"></script>
<script>
    let gridApi;
    const gridOptions = {
        columnDefs: [{
                field: 'id',
                headerName: 'STT',
                minWidth: 50,
                maxWidth: 100,
                filter: false,
                cellRenderer: (params) => params.node.rowIndex + 1
            },
            {
                field: 'images',
                headerName: 'Hình ảnh',
                minWidth: 200,
                filter: false,
                cellClass: 'd-flex align-items-center justify-content-center',
                cellRenderer: (params) =>
                    `<a class="text-decoration-none text-dark" href="/admin/template/category_edit/id/${params.data.id}">
                        <img src="${params.data.images}" alt="image" class="" width="100" height="100" style="object-fit: cover;">
                    </a>`
            },
            {
                field: 'name',
                headerName: 'Loại template',
                minWidth: 300,
                filter: 'agTextColumnFilter',
                cellClass: 'd-flex align-items-center',
                cellRenderer: (params) =>
                    `<a class="text-decoration-none text-dark" href="/admin/template/category_edit/id/${params.data.id}">
                        ${params.value}
                    </a>`
            },
            {
                field: 'description',
                headerName: 'Mô tả',
                minWidth: 200,
                filter: false,
                cellClass: 'd-flex align-items-center',
            },
            {
                field: '',
                headerName: 'Hành động',
                filter: false,
                cellClass: 'd-flex align-items-center justify-content-center',
                minWidth: 200,
                cellRenderer: (params) => {
                    return `<a class="text-decoration-none text-dark" href="/admin/template/category_edit/id/${params.data.id}"><i class="ph-bold ph-pen fs-5"></i></a>`;
                }

            },
        ],
        defaultColDef: {
            flex: 1,
            filter: true,
            floatingFilter: true,
            sortable: true,
            resizable: true
        },
        paginationPageSize: 20,
        pagination: true,
        rowData: <?php echo json_encode($listCategory) ?>,
    };

    document.addEventListener('DOMContentLoaded', function() {
        var gridDiv = document.querySelector('#myGrid');
        new agGrid.Grid(gridDiv, gridOptions);
    });
</script>