<script src="<?php echo URL_ASSETS ?>/js/ag-grid-enterprise.js"></script>
<script>
    let gridApi;
    const gridOptions = {
        columnDefs: [{
                field: 'id',
                headerName: 'STT',
                minWidth: 50,
                maxWidth: 100,
                cellRenderer: (params) => params.node.rowIndex + 1
            },
            {
                field: 'name',
                headerName: 'Tên tiện ích',
                minWidth: 300,
                cellRenderer: (params) =>
                    `<a class="text-decoration-none text-dark" href="<?= BASE_PATH; ?>apps-market/edit/id=${params.data.id}">${params.value}</a>`
            },
            {
                field: 'price',
                headerName: 'Giá',
                minWidth: 200
            },
            {
                field: 'type',
                headerName: 'Loại',
                minWidth: 200,
                cellRenderer: (params) => {
                    const typeMapping = {
                        0: "Nền tảng",
                        1: "Tiện ích"
                    };
                    return typeMapping[params.value] || "Nâng cấp";
                }
            },
            {
                field: 'showview',
                headerName: 'Ẩn/Hiện',
                minWidth: 110,
                cellRenderer: (params) => {
                    const isChecked = params.value == 1 ? 'checked' : '';
                    return `
                        <label class="switch">
                            <input type="checkbox" onclick="handleConfirm(this, ${params.data.id})" ${isChecked}>
                            <span class="slider round"></span>
                        </label>
                    `;
                }
            },
            {
                field: 'description',
                headerName: 'Mô tả',
                minWidth: 200
            },
        ],
        defaultColDef: {
            flex: 1,
            filter: true,
            floatingFilter: true,
            sortable: true,
            resizable: true
        },
        paginationPageSize: 10,
        pagination: true,
        rowData: <?php echo json_encode($listAppsMarket) ?>,
    };

    document.addEventListener('DOMContentLoaded', function() {
        var gridDiv = document.querySelector('#myGrid');
        new agGrid.Grid(gridDiv, gridOptions);
    });
</script>